# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c8412a45f4b742ad99a1c63c8df48ddcd13fa18acc961b9241d3f6f6678bd6bbfcb763907f20a1f62f4dfcacc0e682aca04985127b4089fe7214f1189dd8251

test:
  secret_key_base: 67cea8a7ea4303e355d1f9ca26867827d332a6ef737fa9514c2f2d3a21d746777a53fc000082283d8ea54a3bbf294720859fb0c3d154f97ac0bf1594b477ffbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
